version = 0.1

[default]
[default.global.parameters]
stack_name = "funds-project-api"
region = "ap-south-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Environment=\"dev\" DbSecretName=\"funds-project/postgres\""
image_repositories = []
s3_prefix = "funds-project-api"

